platform:
    - x64

environment:
    PYTHON: "C:\\Python37"

    matrix:
        # Conan development
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          PYVER: py38
          TOXENV: py38-conandev
          CMAKE_GENERATOR: "Visual Studio 16 2019"

        # Conan current version
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          PYVER: py38
          TOXENV: py38-conancurrent
          CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          PYVER: py38
          TOXENV: py38-conancurrent
          CMAKE_GENERATOR: "Visual Studio 16 2019"

        # Conan prev version
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          PYVER: py38
          TOXENV: py38-conanprev
          CMAKE_GENERATOR: "Visual Studio 16 2019"

        # Conan prev-prev version
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          PYVER: py38
          TOXENV: py38-conanprevprev
          CMAKE_GENERATOR: "Visual Studio 16 2019"

    install:
      - cmd: echo "Downloading conan..."
      - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
      - cmd: python -m pip install --upgrade pip
      - cmd: pip.exe install conan
      - cmd: conan user # Create the conan data directory
      - cmd: conan --version

    build_script:
      - cmd: conan remote add magic_get https://api.bintray.com/conan/yehorka9991/magic_get 
      - cmd: conan install .
      - cmd: conan create . yehorka/stable
