environment:
    PYTHON_HOME: "C:\\Python37"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
install:
      echo "Downloading conan..."
      set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
      pip.exe install conan --upgrade
      conan user
      conan --version
build_script:
      conan remote add magic_get https://api.bintray.com/conan/yehorka9991/magic_get 
      conan install .
      conan create . yehorka/stable
