    platform:
      - x64

    environment:
        PYTHON_HOME: "C:\\Python37"

    install:
      - cmd: echo "Downloading conan..."
      - cmd: set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
      - cmd: pip.exe install conan --upgrade
      - cmd: conan user # Create the conan data directory
      - cmd: conan --version

    build_script:
      - cmd: conan remote add magic_get https://api.bintray.com/conan/yehorka9991/magic_get 
      - cmd: conan install .
      - cmd: conan create . yehorka/stable
